packages:
  - name: airquality
    environment:
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
      REDIS_URL: "${REDIS_URL}"
      LANGUAGE: "he"
      TZ: "Asia/Jerusalem"
    functions:
      # Webhook handler - receives incoming WhatsApp messages
      - name: webhook
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000

      # Alert checker - runs on schedule, fetches air quality and sends alerts
      - name: check-alerts
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000
