packages:
  - name: airquality
    environment:
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      REDIS_URL: "${REDIS_URL}"
      LANGUAGE: "he"
      TZ: "Asia/Jerusalem"
    functions:
      # Webhook handler - receives incoming WhatsApp messages
      - name: webhook
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000

      # Telegram webhook handler - receives incoming Telegram messages
      - name: telegram-webhook
        runtime: python:3.11
        web: true
        limits:
          timeout: 30000

      # Alert checker - runs on schedule, fetches air quality and sends alerts
      # Split into 2 batches (~48 stations each) - DO Functions limit: 2 triggers per function
      - name: check-alerts
        runtime: python:3.11
        web: true
        limits:
          timeout: 120000
        triggers:
          # Batch 0: runs at :00, :10, :20, :30, :40, :50
          - name: batch-0
            sourceType: scheduler
            sourceDetails:
              cron: "0,10,20,30,40,50 * * * *"
              body: '{"batch": 0, "total_batches": 2}'
          # Batch 1: runs at :05, :15, :25, :35, :45, :55 (5 min after batch-0)
          - name: batch-1
            sourceType: scheduler
            sourceDetails:
              cron: "5,15,25,35,45,55 * * * *"
              body: '{"batch": 1, "total_batches": 2}'
